<?xml version="1.0"?>
<robot name="lily" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- INCLUDE -->
    <xacro:include filename="$(find lily_description)/urdf/mech/joint.urdf.xacro" />
    <xacro:include filename="$(find lily_description)/urdf/mech/base.urdf.xacro" />
    <xacro:include filename="$(find lily_description)/urdf/mech/wheel.urdf.xacro" />
    <xacro:include filename="$(find lily_description)/urdf/sensors/plugins.urdf.xacro" />
    <xacro:include filename="$(find lily_description)/urdf/sensors/imu.urdf.xacro" />
    <xacro:include filename="$(find lily_description)/urdf/sensors/lidar.urdf.xacro" />
    <xacro:include filename="$(find lily_description)/urdf/sensors/camera.urdf.xacro" />

    <!-- DECLARATION -->

    <xacro:property name="base_length" value="0.200" />
    <xacro:property name="base_width" value="0.445" />
    <xacro:property name="base_height" value="0.129" />
    <xacro:property name="base_mass" value="10" />


    <xacro:property name="wheel_radius" value="0.07162" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="wheel_pos_x" value="0.120" />
    <xacro:property name="wheel_pos_y" value="0.1355" />
    <xacro:property name="wheel_pos_z" value="-0.04788" />
    <xacro:property name="wheel_mass" value=".6" />
    <xacro:property name="wheel_torque" value="20" />

    <xacro:property name="thigh_pos_x" value="${base_width/2}" />
    <xacro:property name="thigh_pos_y" value="0" />
    <xacro:property name="thigh_pos_z" value="0" />

    <!-- FUNCTION(SETUP) -->

    <xacro:base
        length="${base_length}"
        width="${base_width}"
        height="${base_height}"
        mass="${base_mass}"
        wheel_radius="${wheel_radius}"
        wheel_pos_z="${wheel_pos_z}"
    />

    <xacro:joint
        frame_id="left_thigh"
        parent="base_link"
        pos_x="${thigh_pos_x}"
        pos_y="${thigh_pos_y}"
        pos_z="${thigh_pos_z}" />

    <xacro:depth_sensor name="eye">
        <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0" />
    </xacro:depth_sensor>

    <xacro:imu />
</robot>