controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


leg_controller:
  ros__parameters:
    joints:
      - left_thigh_joint
      - left_knee_joint
      - right_thigh_joint
      - right_knee_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: false